### PR TITLE
terraform: use DNS for TLS certificate validation

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by terceiro** [comment]
I'm not 100% sure this is correct yet, feedback appreciated.

terraform locally says this for staging:

```
  + module.webservers.aws_acm_certificate_validation.default
      id:                                 <computed>
      certificate_arn:                    "${aws_acm_certificate.acm-cert.arn}"
      validation_record_fqdns.#:          "2"
      validation_record_fqdns.1172148572: "staging-qa-reports.ctt.linaro.org"
      validation_record_fqdns.3321436767: "staging-qa-reports.linaro.org"
```

cc @danrue

**Comment by danrue** [comment]
I've never used it either.. CC @morancj.

**Comment by morancj** [comment]
I would change the name for your `aws_acm_certificate_validation` to be more specific, maybe reuse the `service_name`?

You need `aws_route53_record`s for each SAN in the certificate, [example](https://github.com/linaro-its/terraform-aws-acm-certificate/blob/0.1.2/main.tf)

**Comment by terceiro** [comment]
> I would change the name for your `aws_acm_certificate_validation` to be more specific, maybe reuse the `service_name`?

it turns out that you can't use variables as resource names (I tried).

> You need `aws_route53_record`s for each SAN in the certificate, [example](https://github.com/linaro-its/terraform-aws-acm-certificate/blob/0.1.2/main.tf)

yes. I added this. but: we generate a cert that is valid for `{staging-,}qa-reports.ctt.linaro.org` and `{staging-,}qa-reports.linaro.org`. however to generate the validation DNS record for staging-qa-reports.linaro.org, our qa-team credentials would need to have access to the linaro.org DNS zone

**Comment by morancj** [comment]
> it turns out that you can't use variables as resource names (I tried).

OK, but what are you going to call the next `aws_acm_certificate_validation` resource?

> access to the linaro.org DNS zone

This is one of the issues which has made me think we need subdomains for each team and/or project, e.g. `ctt.linaro.org.`, `stg.linaro.org.`, `android.build.linaro.org.`, etc. It keeps the namespace clean and more consistent. The issue comes when a team is renamed. Alternatively, I could create the DNS records and certs for you, but of course, that would be more awkward for you and your colleagues when changes are required.

**Comment by terceiro** [comment]
if you take over the certificate *and* the frontend load balancer, I think that would work for me. i.e. you fully manage `*qa-reports.linaro.org` as a frontend to `*qa-reports.ctt.linaro.org`.

```
ITS                            | TEAM
-------------------------------+-----------------------------------
                               |
[foo.linaro.org] --------------+----------->  [foo.ctt.linaro.org]
                               |
                               |
```

This way I don't need access to the linaro.org DNS, and you don't need to get involved with services maintained by other teams; you just set the frontend up and forget about it.

**Comment by terceiro** [comment]
I went to read the [ACM documentation](https://docs.aws.amazon.com/acm/latest/userguide/how-domain-validation-works.html), and AIUI ACM already renews certificates automatically, and the first method of validation is HTTPS requests to the corresponding hostnames.  In the case of qa-reports, this should Just Work and there is nothing to be done.

Unless told otherwise, I will cancel this PR and do nothing here.

**Pull request closed without merging**
