### PR TITLE
ansible: add public and private ssh keys for squad user

### PR DESCRIPTION
**Pull request by chaws**
This will allow a squad running instance to SSH out to other servers, e.g. push change notification for Gerrit.

### CODE REVIEW

**Comment by chaws** [comment]
PS: I had to `export ANSIBLE_VAULT_PASSWORD_FILE=./vault-passwd` in order to get the private key decrypted. Is that the right approach?

**Comment by terceiro** [comment]
> PS: I had to `export ANSIBLE_VAULT_PASSWORD_FILE=./vault-passwd` in order to get the private key decrypted. Is that the right approach?

how exactly did you call ansible? the wrapper scripts in the repository itself already pass the correct arguments to ansible.

**Comment by chaws** [comment]
I ran `./deploy dev`

**Comment by chaws** [comment]
Oh, I noticed the `ansible` script, but that's not called within `deploy`: https://github.com/Linaro/qa-reports.linaro.org/blob/master/ansible/deploy#L40

**Comment by chaws** [comment]
I've opened a PR making dev deploys to also use ansible-passwd, does it makes sense?

**Pull request merged**
